---
- name: Ensure keyring directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add cloudflare apt key
  ansible.builtin.get_url:
    url: https://pkg.cloudflare.com/cloudflare-main.gpg
    dest: /etc/apt/keyrings/cloudflare-main.gpg
    mode: "0644"

- name: Add cloudflared apt repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared {{ ansible_distribution_release }} main"
    filename: cloudflared
    state: present

- name: Install cloudflared
  ansible.builtin.apt:
    name: cloudflared
    state: present
    update_cache: true

- name: Check cloudflared service installed
  ansible.builtin.stat:
    path: /etc/systemd/system/cloudflared.service
  register: cloudflared_service

- name: Install cloudflared connector with token
  ansible.builtin.command:
    cmd: "cloudflared service install {{ cloudflared_token }}"
  when: not cloudflared_service.stat.exists
  no_log: true

- name: Ensure cloudflared running
  ansible.builtin.systemd:
    name: cloudflared
    state: started
    enabled: true
