all:
  children:
    homelab:
      hosts:
        192.168.105.6:
          ansible_user: core-ci
          ansible_ssh_private_key_file: ~/.ssh/ubuntu-server-key
        192.168.14.7:
          ansible_user: core-ci
          ansible_ssh_private_key_file: ~/.ssh/ubuntu-server-key
      children:
        traefik:
          hosts:
            192.168.105.5:
              ansible_user: core-ci
              ansible_ssh_private_key_file: ~/.ssh/ubuntu-server-key
